CREATE TABLE IF NOT EXISTS def_sku_list (
    SKU_ID VARCHAR(100) PRIMARY KEY,
    SITE_ID VARCHAR(100) NOT NULL,
    COLLECT_STATUS VARCHAR(100) NOT NULL DEFAULT 'NEW',
    IF_COLLECT VARCHAR(1) NOT NULL DEFAULT 'Y',
    IMPORT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO def_sku_list (SKU_ID, SITE_ID, COLLECT_STATUS, IF_COLLECT)
VALUES
    ('SKU-MYSQL-001', 'JD', 'NEW', 'Y'),
    ('SKU-MYSQL-002', 'JD', 'SUCCESS', 'Y'),
    ('SKU-MYSQL-003', 'JD', 'PENDING', 'N');
