CREATE TABLE IF NOT EXISTS def_sku_list (
    "SKU_ID" VARCHAR(100) PRIMARY KEY,
    "SITE_ID" VARCHAR(100) NOT NULL,
    "COLLECT_STATUS" VARCHAR(100) NOT NULL DEFAULT 'NEW',
    "IF_COLLECT" VARCHAR(1) NOT NULL DEFAULT 'Y',
    "IMPORT_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO def_sku_list ("SKU_ID", "SITE_ID", "COLLECT_STATUS", "IF_COLLECT")
VALUES
    ('SKU-POSTGRES-001', 'JD', 'NEW', 'Y'),
    ('SKU-POSTGRES-002', 'JD', 'SUCCESS', 'Y'),
    ('SKU-POSTGRES-003', 'JD', 'PENDING', 'N')
ON CONFLICT ("SKU_ID") DO NOTHING;
